# Specify the timezone for checks

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    ignore:
      - dependency-name: "react-scripts"
    schedule:
      interval: "daily"
      time: "04:14"
      timezone: "Australia/Perth"