# Specify the timezone for checks

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:52" # hh:mm formate
      timezone: "Australia/Perth"
    open-pull-requests-limit: 10
    ignore:
      # ignore all 
      - update-types: ["version-update:semver-major"]
      # - dependency-name: "*"
