# Specify the timezone for checks

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:44" # hh:mm formate
      timezone: "Australia/Perth"
    open-pull-requests-limit: 10
    ignore:
      # ignore all GitHub linguist patch updates
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
